services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - name:/usr/local/pgsql/data

volumes:
  name:
    external: true
